feat: Button component add ButtonType, css
PBTP/Webview pull request #14
Opened 2024-03-30 13:53 UTC by gbwlxhd97

시간을 고르는 버튼 만들었습니다.
사실 만들어두신 버튼 컴포넌트에 theme에 css코드만 추가하였고
아래는 디자인 파일입니다.
커밋한 코드에는 아래 디자인파일은 없지만 아래 디자인파일 css는 있습니다.
![image](https://github.com/PBTP/Webview/assets/49021925/38a26e39-053b-4d6d-b51a-e9e5ca31874b)

2024-03-30 16:48 UTC, VictoryJu requested changes

2024-03-30 16:48 UTC, VictoryJu commented on src/components/common/Button/Button.module.scss
> +  &.Gray400 {
음 이름이 좀 애매하네요 다른 Type들은 기능으로 붙였는데 theme변수명이나 기능명이나 하나로 통일하는건 어떨까요?

2024-03-31 00:46 UTC, gbwlxhd97 commented on src/components/common/Button/Button.module.scss
> +  &.Gray400 {
그럴까요
도저히 뭐로하지 싶어서..
@VictoryJu

2024-03-31 03:39 UTC, gbwlxhd97 commented on src/components/common/Button/Button.module.scss
> +  &.Gray400 {
기능명이 직관적이라고 생각하는데
TimeActive로 지을까요??

2024-03-31 09:32 UTC, VictoryJu commented on src/components/common/Button/Button.module.scss
> +  &.Gray400 {
@gbwlxhd97  넵 저는 TimeActive좋습니다

2024-03-31 09:33 UTC, VictoryJu approved these changes

2024-03-31 09:40 UTC, gbwlxhd97 commented
넵 수정했으여~

2024-03-31 09:40 UTC, merged