[feat]: create Review page
PBTP/Webview pull request #28
Opened 2024-07-08 15:28 UTC by gbwlxhd97

## 🎫 [지라 티켓 번호: 179]

<br>

<br>

## 🛠️ 작업 내용

1. 리뷰페이지 작업했습니다.
2. 하나의 페이지에서 view는 다르지만 데이터는 공유해야 하기 때문에 아래 처럼 스텝을 나눴습니다.
크런이때가 생각 나기도 했고 예전에 아래 영상을 본 적 있는데 우리과 비슷하다고 생각해서 인용했습니다.
데이터 관리도 편할 것 같고 스텝이름을 좀 더 직관적으로 이용했습니다.
[참고링크](https://youtu.be/NwLWX2RNVcw?si=luM-x9Q6JnCFVH8N)

```
const [step, setStep] = useState<'SURVEY' | 'REVIEW'>('SURVEY');
```
<br>

<br>

## 📱 작업 화면

|화면 이름|스크린샷|
|:--:|:--:|
|Review 페이지 SURVEY step|<img src = "https://github.com/PBTP/Webview/assets/49021925/2ab2aa0e-03c1-4b42-8bd5-1af87f898131" width ="250">|
|화면 이름|스크린샷|
|Review 페이지 REVIEW step|<img src = "https://github.com/PBTP/Webview/assets/49021925/25b20e9d-af83-41fd-919f-6edfef408d45" width ="250">|
<br>

## 🗒️ Note (optional)

2024-07-08 15:30 UTC, gbwlxhd97 commented on src/pages/Review/Review.tsx
> +        <div className={styles.ReviewHiddenElement}>Hidden</div>
이부분 어떻게 할지 고민중입니다!
의견 주시면 감사하겠습니다!

![image](https://github.com/PBTP/Webview/assets/49021925/2208ebf0-a6ac-4464-8d96-2c65fdc357f7)
헤더가 이렇게 생겨서
가운데 어떻게 둘까하다가..
근데 일단이제 헤더 어떻게 할지 명관님과 논의 해야합니다
@VictoryJu

2024-07-08 15:30 UTC, gbwlxhd97 commented on src/pages/Review/Review.module.scss
> +      // global textarea에 넣으면 안되는지? 승주님과논의
@VictoryJu 의견부탁드립니다!
그리고 global.scss에
textarea 부분에서
`resize: vertical;`
이부분은 저는 none으로 할려고 했는데 위처럼 되어 있어서 이부분도 수정해도 괜찮은지 의견주세요!

2024-07-09 06:09 UTC, VictoryJu requested changes

2024-07-09 06:09 UTC, VictoryJu commented on src/pages/Review/Review.module.scss
> +      // global textarea에 넣으면 안되는지? 승주님과논의
아 요부분 채팅때 vertical이 필요해서 넣어두었었는데요, global의 성격상 resize:none 으로 하는것이 맞다고 생각합니다. global에서 none으로 하고 필요한곳에서 따로 설정해주는것으로 하시지요

2024-07-09 06:09 UTC, VictoryJu commented on src/components/ReviewInfo/ReviewInfo.module.scss
> +  .ReviewHiddenElement {
이 친구는 어떤 기능하는 div인가요?? 나중에 visiblity값이 바뀔수도있는 건가요?

2024-07-09 06:09 UTC, VictoryJu commented on src/pages/Review/Review.tsx
> +  const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
handleReivewText 이름 어떤가요? Change 함수명이 포괄적인것같아서요

2024-07-09 06:09 UTC, VictoryJu commented on src/pages/Review/Review.tsx
> +        <>
Survey와 Review step으로 나뉘는부분 컴포넌트로 따로 빼실 예정일까요?

2024-07-09 06:09 UTC, VictoryJu commented on src/pages/Review/Review.tsx
> +        <div className={styles.ReviewHiddenElement}>Hidden</div>
헤더 명관님과 논의해보고 저희가 만들어야되면 그때 한번 같이 보시죠

2024-07-09 06:13 UTC, VictoryJu commented on src/pages/Review/Review.tsx
> +  const [step, setStep] = useState<'SURVEY' | 'REVIEW'>('SURVEY');
step 굿이염 (따봉티콘)

2024-07-09 06:18 UTC, gbwlxhd97 commented on src/components/ReviewInfo/ReviewInfo.module.scss
> +  .ReviewHiddenElement {
<img width="783" alt="image" src="https://github.com/PBTP/Webview/assets/49021925/dd028228-9325-4fc2-a3ac-cf94e0c3a4f7">
이부분 때문에
3개를 두고
DeleteIcon
Title
hidden div 이렇게 표현했습니다!

2024-07-09 06:19 UTC, gbwlxhd97 commented on src/pages/Review/Review.tsx
> +        <>
네 나중에 컴포넌트 분리할 것 같아요
지금은 데이터 형식 아직 안정해져서 해당 페이지에서 전부 처리했습니다.
그런데 동일한 css가 많아서 분리해도 클래스명은 동일한 아이들이 많아요 이건 어떻게 처리하는게 좋을까요?
@VictoryJu

2024-07-09 06:19 UTC, VictoryJu commented on src/components/ReviewInfo/ReviewInfo.module.scss
> +  .ReviewHiddenElement {
아 outdate로 pr이넘어갔길래 못봤습니다 확인했습니다

2024-07-09 06:21 UTC, VictoryJu commented on src/pages/Review/Review.tsx
> +        <>
클래스명이 동일한게 많다면 module.scss를 공통으로 하나만 사용하는것도 괜찮을것같긴합니다.

2024-07-10 11:22 UTC, VictoryJu commented
@gbwlxhd97 
main 브랜치에 #27 PR이 합쳐져서요, rebase후 푸쉬 다시 부탁드립니다!

2024-07-16 06:57 UTC, gbwlxhd97 commented
@VictoryJu 
rebase후에 코맨트 주신 것들 반영하여 머지했습니다~

2024-07-16 06:57 UTC, merged